---
- name: Install necessary packages
  become: True
  apt:
    name: ["certbot", "python3-certbot-nginx"]
    state: present

- name: Install Certificate
  become: True
  shell: "export PATH=$PATH:/sbin && /usr/bin/certbot --nginx -n --agree-tos --redirect --email {{ admin_email  }} -d {{ domains }}"
