---
- name: Create iptables directory
  become: yes
  file:
    path: '/etc/iptables'
    state: directory
    owner: root
    group: root
    mode: 0700

- name: Settle ipv4 rules
  become: True
  block:
    - name: Copy ipv4 rules
      template:
        src: "ipv4.rules"
        dest: "/etc/iptables/ipv4.rules"
        owner: root
        group: root
        mode: 0700
    - name: Copy pre-ipv4 rules
      copy:
        src: "pre-ipv4.rules"
        dest: "/etc/iptables/pre-ipv4.rules"
        owner: root
        group: root
        mode: 0700
  when: ansible_facts["default_ipv4"].keys()|length > 0

- name: Settle ipv6 rules
  become: True
  block:
    - name: Copy ipv6 rules
      template:
        src: "ipv6.rules"
        dest: "/etc/iptables/ipv6.rules"
        owner: root
        group: root
        mode: 0700
    - name: Copy pre-ipv6 rules
      copy:
        src: "pre-ipv6.rules"
        dest: "/etc/iptables/pre-ipv6.rules"
        owner: root
        group: root
        mode: 0700
  when: ansible_facts["default_ipv6"].keys()|length > 0

- name: Copy Files and Templates
  become: True
  block:
    - name: Copy starting template scripts
      template:
        src: "{{ item }}.j2"
        dest: "/etc/iptables/{{ item }}"
        owner: root
        group: root
        mode: 0700
      with_items:
        - "firewall.start"
        - "pre-firewall.start"
    - name: Copy service files
      copy:
        src: "{{ item }}"
        dest: "/etc/systemd/system/{{ item }}"
        owner: root
        group: root
        mode: 0644
      with_items:
        - "firewall.service"
        - "pre-firewall.service"

- name: Reread systemd configuration
  become: True
  systemd:
    daemon_reload: yes

- name: Enable firewall
  service:
    name: "{{ item }}"
    enabled: yes
    state: stopped
  become: True
  with_items:
    - "pre-firewall"
    - "firewall"
