---
- name: "Start Maintenance Mode"
  shell:
    cmd: "{{ ansible_user_dir }}/.local/bin/start_maintenance"

- name: "Stop Gunicorn"
  ansible.builtin.service:
    name: gunicorn
    state: stopped

- name: "Copy .env to production"
  copy:
    src: "{{ lookup('env', 'DOTENV_FILE_PATH') }}"
    dest: "{{ lookup('env', 'POET_PROJECT_PATH') }}/.env"
    owner: "{{ ansible_ssh_user }}"
    group: "{{ ansible_ssh_user }}"
    mode: 0400
