---
- name: "Stop when Postgresql environment variables are undefined"
  meta: end_play
  when: django_postgres_user == "" or django_postgres_user_pass == ""

- name: "Stop when Nginx environment variables are undefined"
  meta: end_play
  when: server_domain_name == "" or domains == "" or django_admin_path == ""

- name: "Stop when maintenance environment variables are undefined"
  meta: end_play
  when: lookup('env', 'ANSIBLE_DOTENV_FILE_PATH') == "" or lookup('env', 'POET_PROJECT_PATH') == ""
